//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R3_VillagePeople_Mahtimokit.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string default_office {
            get {
                return ((string)(this["default_office"]));
            }
            set {
                this["default_office"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2017-05-15")]
        public global::System.DateTime default_history_end_date {
            get {
                return ((global::System.DateTime)(this["default_history_end_date"]));
            }
            set {
                this["default_history_end_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool default_is_history_end_date_today {
            get {
                return ((bool)(this["default_is_history_end_date_today"]));
            }
            set {
                this["default_is_history_end_date_today"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Käyttäjä")]
        public string user_name {
            get {
                return ((string)(this["user_name"]));
            }
            set {
                this["user_name"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\VP_Database.m" +
            "df;Integrated Security=True;Connect Timeout=30")]
        public string VP_DatabaseConnectionString {
            get {
                return ((string)(this["VP_DatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.0%")]
        public string default_penalty_interest {
            get {
                return ((string)(this["default_penalty_interest"]));
            }
            set {
                this["default_penalty_interest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12 pv")]
        public string default_remark_time {
            get {
                return ((string)(this["default_remark_time"]));
            }
            set {
                this["default_remark_time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Village People\r\nY-tunnus: 123\r\nwww.vpp.fi")]
        public string default_infobox_1 {
            get {
                return ((string)(this["default_infobox_1"]));
            }
            set {
                this["default_infobox_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tiekatutie 1\r\n29019 tiekatula\r\n")]
        public string default_infobox_2 {
            get {
                return ((string)(this["default_infobox_2"]));
            }
            set {
                this["default_infobox_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("puhelin\r\n040 000 000 00\r\n")]
        public string default_infobox_3 {
            get {
                return ((string)(this["default_infobox_3"]));
            }
            set {
                this["default_infobox_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fax\r\n040 1200 00 \r\n")]
        public string default_infobox_4 {
            get {
                return ((string)(this["default_infobox_4"]));
            }
            set {
                this["default_infobox_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pankki\r\nossuus pankki\r\nbleb")]
        public string default_infobox_5 {
            get {
                return ((string)(this["default_infobox_5"]));
            }
            set {
                this["default_infobox_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FI32 1515 1613 13")]
        public string default_IBAN {
            get {
                return ((string)(this["default_IBAN"]));
            }
            set {
                this["default_IBAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FAFIFAFHIFF")]
        public string default_BIC {
            get {
                return ((string)(this["default_BIC"]));
            }
            set {
                this["default_BIC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Village peiple ay")]
        public string default_receiver {
            get {
                return ((string)(this["default_receiver"]));
            }
            set {
                this["default_receiver"] = value;
            }
        }
    }
}
